products = [
  {
    "_id": "1",
    "name": "Bluetooth Headphones",
    "image": "images/Product.jpg",
    "description": "This are some quality headphones with superb sound quality .",
    "brand": "Apple",
    "category": "Electronics",
    "price": "100.34",
    "countInStock": "0",
    "rating": "4.5",
    "numReviews": "12",
  },
  {
    "_id": "2",
    "name": "Big Headphones",
    "image": "images/Product.jpg",
    "description": "This are some quality headphones with superb sound quality .",
    "brand": "loreal",
    "category": "Beauty",
    "price": "100.34",
    "countInStock": "20",
    "rating": "4.5",
    "numReviews": "12",
  },
  {
    "_id": "3",
    "name": "Luron",
    "image": "images/Product.jpg",
    "description": "This are some quality headphones with superb sound quality .",
    "brand": "Luron",
    "category": "Beauty",
    "price": "100.34",
    "countInStock": "20",
    "rating": "2.5",
    "numReviews": "12",
  },
  {
    "_id": "4",
    "name": "Gaming pad",
    "image": "images/Product.jpg",
    "description": "This are some quality headphones with superb sound quality .",
    "brand": "Sony",
    "category": "Electronics",
    "price": "100.34",
    "countInStock": "20",
    "rating": "5",
    "numReviews": "12",
  },
  {
    "_id": "5",
    "name": "Hair cutter",
    "image": "images/Product.jpg",
    "description": "This are some quality headphones with superb sound quality .",
    "brand": "Hair",
    "category": "Beauty",
    "price": "100.34",
    "countInStock": "20",
    "rating": "2.5",
    "numReviews": "12",
  },
  {
    "_id": "6",
    "name": "Camera",
    "image": "images/Product.jpg",
    "description": "This are some quality headphones with superb sound quality .",
    "brand": "Nickon",
    "category": "Electronics",
    "price": "100.34",
    "countInStock": "20",
    "rating": "3.5",
    "numReviews": "12",
  },
];


